export enum CountryCode {
  AR = 'AR',
  BO = 'BO',
  BR = 'BR',
  CL = 'CL',
  CO = 'CO',
  CR = 'CR',
  EC = 'EC',
  MX = 'MX',
  PE = 'PE',
  PY = 'PY',
  UY = 'UY',
  VE = 'VE',
  US = 'US',
  ES = 'ES',
}

export const COUNTRY_DIAL_CODES: Record<CountryCode, string> = {
  [CountryCode.AR]: '+54',
  [CountryCode.BO]: '+591',
  [CountryCode.BR]: '+55',
  [CountryCode.CL]: '+56',
  [CountryCode.CO]: '+57',
  [CountryCode.CR]: '+506',
  [CountryCode.EC]: '+593',
  [CountryCode.MX]: '+52',
  [CountryCode.PE]: '+51',
  [CountryCode.PY]: '+595',
  [CountryCode.UY]: '+598',
  [CountryCode.VE]: '+58',
  [CountryCode.US]: '+1',
  [CountryCode.ES]: '+34',
};

export const COUNTRY_NAMES: Record<CountryCode, string> = {
  [CountryCode.AR]: 'Argentina',
  [CountryCode.BO]: 'Bolivia',
  [CountryCode.BR]: 'Brasil',
  [CountryCode.CL]: 'Chile',
  [CountryCode.CO]: 'Colombia',
  [CountryCode.CR]: 'Costa Rica',
  [CountryCode.EC]: 'Ecuador',
  [CountryCode.MX]: 'México',
  [CountryCode.PE]: 'Perú',
  [CountryCode.PY]: 'Paraguay',
  [CountryCode.UY]: 'Uruguay',
  [CountryCode.VE]: 'Venezuela',
  [CountryCode.US]: 'Estados Unidos',
  [CountryCode.ES]: 'España',
};
